nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports: 
        - "80:80"
        - "443:443"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - /data/certs/:/etc/nginx/certs:ro
        - /etc/nginx/vhost.d
        - /usr/share/nginx/html
    labels:
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_prox

letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
        - /data/certs:/etc/nginx/certs:rw
        - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
        - nginx-proxy:rw

nginx:
    image: tutum/nginx
    restart: always

    links:
        - phpfpm
    volumes:
        - ./nginx/front/default:/etc/nginx/sites-available/default
        - ./nginx/front/default:/etc/nginx/sites-enabled/default

        - ./logs/front/nginx-error.log:/var/log/nginx/error.log
        - ./logs/front/nginx-access.log:/var/log/nginx/access.log

    expose:
        - 80
        - 443
        
    environment:
        - VIRTUAL_HOST=sisglobal.local,www.sisglobal.local
        - LETSENCRYPT_HOST=sisglobal.local,www.sisglobal.local
        - LETSENCRYPT_EMAIL=sysadm2.acero@gmail.com

phpfpm:
    image: php:7-fpm
    restart: always
    expose:
        - 9000
    volumes:
        - ./frontend:/usr/share/nginx/html

nginxback:
    image: tutum/nginx
    restart: always

    links:
        - phpfpm2
    volumes:
        - ./nginx/back/default:/etc/nginx/sites-available/default
        - ./nginx/back/default:/etc/nginx/sites-enabled/default

        - ./logs/back/nginx-error.log:/var/log/nginx/error.log
        - ./logs/back/nginx-access.log:/var/log/nginx/access.log

    expose:
        - 80
        - 443
        
    environment:
        - VIRTUAL_HOST=backsisglobal.local,www.backsisglobal.local
        - LETSENCRYPT_HOST=backsisglobal.local,www.backsisglobal.local
        - LETSENCRYPT_EMAIL=sysadm2.acero@gmail.com

phpfpm2:
    image: php:7-fpm
    restart: always
    expose:
        - 9000
    volumes:
        - ./backend:/usr/share/nginx/html

mysql:
    image: mysql:latest
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: admin
    ports:
        - "3306:3306" 

node-api:
    image: node:12
    restart: always
    ports: 
        - "8001:8000"
    volumes: 
        - ./nodebackend:/app
    environment:
        - DB_CONNECT = mongodb+srv://tenhitokiri:En1el2es1@cluster0-zfj4f.mongodb.net/jwt?retryWrites=true&w=majority
        - PORT = 8000
        - TOKEN_SECRET = slkdjfsladkfjlsdae
    
    working_dir: /app
    command: npm start


